In [7]:
pwd

'/mmfs1/data/aglinska/BC-fMRI-AE/Notebooks'

In [8]:
import pandas as pd
import os

In [9]:
indir = '../../data/ABIDE2/RawData/'

In [11]:
folders = os.listdir(indir)
folders.sort()

'../../data/ABIDE2/RawData/ABIDEII-GU_1/participants.tsv'

In [36]:
os.path.exists(df_fn)
df_fn

'../../data/ABIDE2/RawData/ABIDEII-GU_1/participants.tsv'

In [38]:
pd.read_csv(df_fn,'delimiter','\t',encoding = "ISO-8859-1")

,site_id,participant_id,ndar_guid,dx_group,pdd_dsm_iv_tr,asd_dsm_5,age_at_scan,sex,handedness_category,handedness_scores,...,adi_r_c3_total,adi_r_c4_repetitive_use_objects,adi_r_c4_higher,adi_r_c4_unusual_sensory_interests,adi_r_c4_total,adi_r_d_age_parent_noticed,adi_r_d_age_first_single_words,adi_r_d_age_first_phrases,adi_r_d_age_when_abnormality,adi_r_d_interviewer_judgment
0,ABIDEII-GU_1,28752,NaN,1,1.0,NaN,13.076712,1,1.0,NaN,...,1.0,2.0,2.0,1.0,2.0,1.0,0.0,0.0,1.0,1.0
1,ABIDEII-GU_1,28754,NaN,1,3.0,NaN,9.298630,1,1.0,NaN,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0
2,ABIDEII-GU_1,28756,NaN,1,2.0,NaN,12.490411,2,2.0,NaN,...,2.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0
3,ABIDEII-GU_1,28758,NaN,1,2.0,NaN,9.868493,2,2.0,NaN,...,2.0,0.0,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
4,ABIDEII-GU_1,28761,NaN,1,2.0,NaN,11.484932,1,1.0,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,ABIDEII-GU_1,28841,NaN,2,0.0,NaN,8.723288,2,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,ABIDEII-GU_1,28842,NaN,2,0.0,NaN,8.408219,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,ABIDEII-GU_1,28845,NaN,2,0.0,NaN,8.390000,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,ABIDEII-GU_1,28846,NaN,2,0.0,NaN,8.740000,2,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,ABIDEII-GU_1,28847,NaN,2,0.0,NaN,10.490000,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
f = 0
df = pd.read_csv(os.path.join(indir,folders[f],'participants.tsv'),'delimiter','\t')

for f in range(1,len(folders)):
    df_fn = os.path.join(indir,folders[f],'participants.tsv')
    if os.path.exists(df_fn):
        df = df.append(pd.read_csv(df_fn,'delimiter','\t',encoding = "ISO-8859-1"))
df.shape

(1007, 348)

In [40]:
df.to_csv('../Data/ABIDE2_df.csv')